### ISSUE TITLE
Zips created in windows are not valid in linux due to the invalid separator

### ISSUE THREAD

**Issue by bjg2** [saracen/fastzip#25]
Even if Archive is provided with the files map that has "/" separator in keys it is changed to "\\" in the system calls in the ArchiveWithContext. When "\\" is used as separator linux sees invalid folder structure.

Fix: in ArchiveWithContext change 
```
fileInfoHeader(rel, fi, hdr)
```

to

```
fileInfoHeader(strings.ReplaceAll(rel, "\\", "/"), fi, hdr)
```

or some similar solution using os.PathSeparator

**Comment by saracen** [comment]
Thank you @bjg2! This is a regression, previously `filepath.ToSlash` was used to always force path separators to use a forward slash. I'll correct this now.

**Comment by saracen** [comment]
This was fixed with https://github.com/saracen/fastzip/pull/26 - I'll create a release shortly.

**Comment by bjg2** [comment]
That's great! I did `go get github.com/saracen/fastzip` and it changed from v0.1.0 to v0.1.4, but it didn't fix the issue for me, I still see the same behavior. Not released still?
